CREATE TABLE user_info (
  id DECIMAL(20) GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  create_time datetime DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  update_time datetime DEFAULT NULL,
  UNIQUE   (email),
  UNIQUE  (name)
) ;

